id = "colorizer"
name = "Colorizer"
version = "1.0.6"
schema_version = 1
authors = ["Tamim Hasan <info@tamimhasan.com>"]
description = "Colorizer is a vibrant Zed code editor theme that enhances readability with rich, contrasting colors, making your coding experience both efficient and enjoyable."
repository = "https://github.com/tamimhasandev/colorizer"
